# Generated by Django 3.1.6 on 2021-02-10 09:13

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychotherapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('photo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media')),
                ('methods', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'psychotherapist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PsychotherapistRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('creation_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'psychotherapist_raw_data',
                'managed': False,
            },
        ),
    ]
