# Generated by Django 3.1.6 on 2021-02-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychotherapist',
            options={'managed': False, 'verbose_name': 'психотерапевт', 'verbose_name_plural': 'психотерапевты'},
        ),
    ]
